from jinja2 import Template

from app.reports.context import ReportContext

_TEMPLATE = Template(
    """
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>NAVIXA AI - {{ report_type|capitalize }} Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #1a1a1a; }
    h1 { color: #0B3D91; }
    .meta { color: #555; margin-bottom: 24px; }
    table { border-collapse: collapse; width: 100%; margin-top: 16px; }
    th, td { border: 1px solid #ccc; padding: 8px; text-align: left; font-size: 13px; }
    th { background: #0B3D91; color: white; }
    .severity-critical { color: #B71C1C; font-weight: bold; }
    .severity-high { color: #D32F2F; font-weight: bold; }
    .severity-medium { color: #F57C00; }
    .severity-low { color: #388E3C; }
    .severity-informational { color: #555; }
  </style>
</head>
<body>
  <h1>NAVIXA AI &mdash; {{ report_type|capitalize }} Report</h1>
  <div class="meta">
    Tenant: {{ context.tenant_name }} ({{ context.provider|upper }})<br>
    Audit Job: {{ context.audit_job_id }}<br>
    Status: {{ context.job_status }}<br>
    Audit Created: {{ context.created_at }}
  </div>

  {% if context.exec_summary %}
  <h2>Executive Summary</h2>
  <p>{{ context.exec_summary }}</p>
  {% endif %}

  <h2>Findings Summary</h2>
  <p>
    {% for severity, count in context.severity_counts.items() %}
      <span class="severity-{{ severity }}">{{ severity|capitalize }}: {{ count }}</span>&nbsp;&nbsp;
    {% else %}
      No findings identified.
    {% endfor %}
  </p>

  {% if report_type != "executive" %}
  <h2>Detailed Findings</h2>
  <table>
    <tr><th>Module</th><th>Type</th><th>Severity</th><th>Title</th><th>Status</th></tr>
    {% for finding in context.findings %}
    <tr>
      <td>{{ finding.module }}</td>
      <td>{{ finding.finding_type }}</td>
      <td class="severity-{{ finding.severity }}">{{ finding.severity }}</td>
      <td>{{ finding.title }}</td>
      <td>{{ finding.status }}</td>
    </tr>
    {% endfor %}
  </table>
  {% endif %}

  <p style="margin-top: 32px; color: #999; font-size: 11px;">
    Generated by NAVIXA AI &mdash; Transforming Cloud Network Complexity Into Actionable Intelligence.
  </p>
</body>
</html>
"""
)


def render_html(context: ReportContext, report_type: str) -> str:
    return _TEMPLATE.render(context=context, report_type=report_type)
