"""initial schema

Revision ID: a903175f9941
Revises: 
Create Date: 2026-07-02 13:03:11.358600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a903175f9941'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cloud_tenants',
    sa.Column('provider', sa.Enum('aws', 'azure', 'gcp', 'oci', name='cloud_provider'), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('external_tenant_id', sa.String(length=255), nullable=False),
    sa.Column('sso_login_url', sa.String(length=500), nullable=True),
    sa.Column('region_info', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('audit_jobs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'discovering', 'graphing', 'validating', 'pathfinding', 'analyzing', 'reporting', 'completed', 'failed', 'partial', name='audit_job_status'), nullable=False),
    sa.Column('hub_selection', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['cloud_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cloud_scopes',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.Enum('account', 'subscription', 'project', 'compartment', name='cloud_scope_type'), nullable=False),
    sa.Column('external_scope_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['cloud_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_job_scopes',
    sa.Column('audit_job_id', sa.UUID(), nullable=False),
    sa.Column('cloud_scope_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'partial', 'failed', name='scope_job_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cloud_scope_id'], ['cloud_scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('audit_job_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.Enum('validate', 'pathfinder', name='finding_module'), nullable=False),
    sa.Column('finding_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'informational', name='finding_severity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('affected_resource_ids', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', 'false_positive', name='finding_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network_resources',
    sa.Column('audit_job_scope_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.Enum('network', 'subnet', 'route_table', 'route', 'gateway', 'firewall', 'security_group', 'network_interface', 'load_balancer', 'endpoint', 'compute_instance', 'peering_connection', 'public_ip', name='network_resource_type'), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('native_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('graph_node_id', sa.String(length=255), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_scope_id'], ['audit_job_scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_collection_status',
    sa.Column('audit_job_scope_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('success', 'partial', 'failed', name='resource_collection_status'), nullable=False),
    sa.Column('error_detail', sa.String(), nullable=True),
    sa.Column('items_collected', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_scope_id'], ['audit_job_scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_collection_status')
    op.drop_table('network_resources')
    op.drop_table('findings')
    op.drop_table('audit_job_scopes')
    op.drop_table('cloud_scopes')
    op.drop_table('audit_jobs')
    op.drop_table('user_roles')
    op.drop_table('cloud_tenants')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
