"""add ai_insights, reports, scheduled_discoveries, resource_changes

Revision ID: ddc13cb00a79
Revises: b1c2d3e4f5a6
Create Date: 2026-07-02 17:48:39.506538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddc13cb00a79'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_discoveries',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('scope_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('hub_selection', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['cloud_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('audit_job_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.Enum('executive', 'technical', 'compliance', name='report_type'), nullable=False),
    sa.Column('format', sa.Enum('pdf', 'excel', 'html', name='report_format'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'completed', 'failed', name='report_status'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_changes',
    sa.Column('audit_job_id', sa.UUID(), nullable=False),
    sa.Column('compared_to_audit_job_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('native_id', sa.String(length=255), nullable=False),
    sa.Column('change_type', sa.Enum('added', 'removed', 'modified', name='resource_change_type'), nullable=False),
    sa.Column('previous_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['compared_to_audit_job_id'], ['audit_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_insights',
    sa.Column('audit_job_id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=True),
    sa.Column('insight_type', sa.Enum('root_cause', 'recommendation', 'exec_summary', 'topology_explanation', name='insight_type'), nullable=False),
    sa.Column('ai_provider', sa.Enum('claude', 'openai', 'azure_openai', 'gemini', 'bedrock', name='ai_provider_name'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_insights')
    op.drop_table('resource_changes')
    op.drop_table('reports')
    op.drop_table('scheduled_discoveries')
    # ### end Alembic commands ###
